# ?description=MatchClz
# ?shortcut=
import json

from json import JSONEncoder
from com.pnfsoftware.jeb.client.api import IScript
from com.pnfsoftware.jeb.core.units.code.android import IDexUnit


class MyEncoder(JSONEncoder):
    def default(self, obj):
        return obj.__dict__


class MethodFeature:
    pass


BaseTypes = [
    "[[[I",
    "[[B",
    "[[C",
    "[[I",
    "[[J",
    "[[Ljava/lang/String;",
    "[[S",
    "[B",
    "[C",
    "[D",
    "[F",
    "[I",
    "[J",
    "[S",
    "[Z",
    "B",
    "C",
    "D",
    "F",
    "I",
    "J",
    "S",
    "Z",
    "[Landroid/content/Intent;",
    "[Landroid/content/pm/Signature;",
    "[Landroid/database/CursorWindow;",
    "[Landroid/graphics/drawable/Drawable;",
    "[Landroid/graphics/Paint;",
    "[Landroid/graphics/Path;",
    "[Landroid/graphics/RectF;",
    "[Landroid/graphics/Shader;",
    "[Landroid/hardware/Camera$CameraInfo;",
    "[Landroid/hardware/camera2/params/MeteringRectangle;",
    "[Landroid/media/MediaCodecInfo;",
    "[Landroid/net/http/ConnectionThread;",
    "[Landroid/net/http/IdleCache$Entry;",
    "[Landroid/net/Uri;",
    "[Landroid/text/InputFilter;",
    "[Landroid/text/style/ClickableSpan;",
    "[Landroid/text/style/ImageSpan;",
    "[Landroid/text/TextUtils$TruncateAt;",
    "[Landroid/view/View;",
    "[Landroidx/fragment/app/BackStackRecordState;",
    "[Lcom/android/internal/http/multipart/Part;",
    "[Lcom/facebook/infer/annotation/Nullsafe$Mode;",
    "[Lcom/facebook/lite/loginWithFacebook/wrapper/LoginMethodHandler;",
    "[Lcom/facebook/lite/msys/provider/MsysProvider;",
    "[Lcom/facebook/onecamera/corecomponents/threading/basic/ThreadPoolImpl$LifeStatus;",
    "[Lcom/facebook/privacy/zone/policy/ZonePolicy;",
    "[Lcom/facebook/rendercore/RenderTreeNode;",
    "[Lcom/facebook/video/heroplayer/ipc/ParcelableFormat;",
    "[Lcom/facebook/video/heroplayer/ipc/VideoMemoryState;",
    "[Lcom/google/android/exoplayer2/drm/DrmInitData$SchemeData;",
    "[Lcom/google/android/exoplayer2/Format;",
    "[Lcom/google/android/exoplayer2/metadata/emsg/EventMessage;",
    "[Lcom/google/android/exoplayer2/metadata/id3/Id3Frame;",
    "[Lcom/google/android/exoplayer2/metadata/Metadata$Entry;",
    "[Lcom/google/android/exoplayer2/metadata/Metadata;",
    "[Lcom/google/android/exoplayer2/source/TrackGroupArray;",
    "[Lcom/google/android/exoplayer2/Timeline;",
    "[Lcom/google/android/gms/common/api/Scope;",
    "[Lcom/google/android/gms/common/Feature;",
    "[Lcom/google/android/gms/common/zzj;",
    "[Lcom/google/android/gms/safetynet/HarmfulAppsData;",
    "[Lcom/google/common/collect/Maps$EntryFunction;",
    "[Lcom/google/errorprone/annotations/Modifier;",
    "[Lcom/google/j2objc/annotations/LoopTranslation$LoopStyle;",
    "[Lcom/google/j2objc/annotations/ReflectionSupport$Level;",
    "[Ldalvik/system/DexFile;",
    "[Lexoplayer2/av1/src/Dav1dScalingMode;",
    "[Ljava/io/File;",
    "[Ljava/io/OutputStream;",
    "[Ljava/io/RandomAccessFile;",
    "[Ljava/lang/Boolean;",
    "[Ljava/lang/Class;",
    "[Ljava/lang/Integer;",
    "[Ljava/lang/Object;",
    "[Ljava/lang/String;",
    "[Ljava/lang/Throwable;",
    "[Ljava/net/InetSocketAddress;",
    "[Ljava/nio/ByteBuffer;",
    "[Ljava/security/cert/X509Certificate;",
    "[Ljava/util/AbstractMap$SimpleEntry;",
    "[Ljava/util/HashMap;",
    "[Ljava/util/List;",
    "[Ljava/util/Map;",
    "[Ljavax/net/ssl/TrustManager;",
    "[Ljavax/net/ssl/X509TrustManager;",
    "[Lorg/apache/http/conn/routing/RouteInfo$LayerType;",
    "[Lorg/apache/http/conn/routing/RouteInfo$TunnelType;",
    "[Lorg/apache/http/Header;",
    "[Lorg/apache/http/HttpHost;",
    "[Lorg/apache/http/impl/auth/NTLMScheme$State;",
    "[Lorg/apache/http/NameValuePair;",
    "Landroid/accounts/Account;",
    "Landroid/animation/Animator$AnimatorListener;",
    "Landroid/animation/Animator;",
    "Landroid/animation/AnimatorSet;",
    "Landroid/animation/ArgbEvaluator;",
    "Landroid/animation/ObjectAnimator;",
    "Landroid/animation/TimeInterpolator;",
    "Landroid/animation/ValueAnimator$AnimatorUpdateListener;",
    "Landroid/animation/ValueAnimator;",
    "Landroid/app/Activity;",
    "Landroid/app/ActivityManager$MemoryInfo;",
    "Landroid/app/ActivityManager$RunningAppProcessInfo;",
    "Landroid/app/ActivityManager;",
    "Landroid/app/ActivityThread;",
    "Landroid/app/AlarmManager;",
    "Landroid/app/AlertDialog;",
    "Landroid/app/Application$ActivityLifecycleCallbacks;",
    "Landroid/app/Application;",
    "Landroid/app/AppOpsManager$OnOpChangedListener;",
    "Landroid/app/Dialog;",
    "Landroid/app/job/JobInfo;",
    "Landroid/app/job/JobParameters;",
    "Landroid/app/job/JobScheduler;",
    "Landroid/app/job/JobWorkItem;",
    "Landroid/app/Notification$Builder;",
    "Landroid/app/Notification;",
    "Landroid/app/NotificationChannel;",
    "Landroid/app/NotificationManager;",
    "Landroid/app/PendingIntent;",
    "Landroid/app/usage/NetworkStats$Bucket;",
    "Landroid/app/usage/NetworkStatsManager;",
    "Landroid/bluetooth/BluetoothAdapter;",
    "Landroid/bluetooth/le/BluetoothLeScanner;",
    "Landroid/content/BroadcastReceiver$PendingResult;",
    "Landroid/content/BroadcastReceiver;",
    "Landroid/content/ClipData;",
    "Landroid/content/ComponentName;",
    "Landroid/content/ContentResolver;",
    "Landroid/content/Context;",
    "Landroid/content/DialogInterface$OnCancelListener;",
    "Landroid/content/DialogInterface$OnDismissListener;",
    "Landroid/content/Intent;",
    "Landroid/content/IntentFilter;",
    "Landroid/content/IntentSender$SendIntentException;",
    "Landroid/content/IntentSender;",
    "Landroid/content/pm/ApplicationInfo;",
    "Landroid/content/pm/PackageInfo;",
    "Landroid/content/pm/PackageManager;",
    "Landroid/content/pm/ProviderInfo;",
    "Landroid/content/pm/Signature;",
    "Landroid/content/res/AssetFileDescriptor;",
    "Landroid/content/res/AssetManager$AssetInputStream;",
    "Landroid/content/res/AssetManager;",
    "Landroid/content/res/ColorStateList;",
    "Landroid/content/res/Resources$Theme;",
    "Landroid/content/res/Resources;",
    "Landroid/content/ServiceConnection;",
    "Landroid/content/SharedPreferences;",
    "Landroid/content/UriMatcher;",
    "Landroid/database/ContentObserver;",
    "Landroid/database/Cursor;",
    "Landroid/database/DataSetObservable;",
    "Landroid/graphics/Bitmap$Config;",
    "Landroid/graphics/Bitmap;",
    "Landroid/graphics/Canvas;",
    "Landroid/graphics/ColorFilter;",
    "Landroid/graphics/ColorSpace;",
    "Landroid/graphics/drawable/Animatable;",
    "Landroid/graphics/drawable/BitmapDrawable;",
    "Landroid/graphics/drawable/ColorDrawable;",
    "Landroid/graphics/drawable/Drawable;",
    "Landroid/graphics/drawable/GradientDrawable;",
    "Landroid/graphics/drawable/StateListDrawable;",
    "Landroid/graphics/Matrix;",
    "Landroid/graphics/Movie;",
    "Landroid/graphics/Paint$FontMetricsInt;",
    "Landroid/graphics/Paint;",
    "Landroid/graphics/Path;",
    "Landroid/graphics/PathMeasure;",
    "Landroid/graphics/Point;",
    "Landroid/graphics/PointF;",
    "Landroid/graphics/PorterDuff$Mode;",
    "Landroid/graphics/PorterDuffXfermode;",
    "Landroid/graphics/Rect;",
    "Landroid/graphics/RectF;",
    "Landroid/graphics/Shader;",
    "Landroid/graphics/SurfaceTexture;",
    "Landroid/graphics/Typeface;",
    "Landroid/hardware/Camera$ErrorCallback;",
    "Landroid/hardware/Camera$Parameters;",
    "Landroid/hardware/Camera$PreviewCallback;",
    "Landroid/hardware/Camera$ShutterCallback;",
    "Landroid/hardware/Camera;",
    "Landroid/hardware/camera2/CameraCaptureSession;",
    "Landroid/hardware/camera2/CameraCharacteristics;",
    "Landroid/hardware/camera2/CameraDevice;",
    "Landroid/hardware/camera2/CameraExtensionCharacteristics;",
    "Landroid/hardware/camera2/CameraExtensionSession;",
    "Landroid/hardware/camera2/CameraManager;",
    "Landroid/hardware/camera2/CaptureFailure;",
    "Landroid/hardware/camera2/CaptureRequest$Builder;",
    "Landroid/hardware/camera2/params/StreamConfigurationMap;",
    "Landroid/hardware/camera2/TotalCaptureResult;",
    "Landroid/hardware/display/DisplayManager;",
    "Landroid/hardware/display/VirtualDisplay;",
    "Landroid/hardware/SensorManager;",
    "Landroid/location/Location;",
    "Landroid/location/LocationManager;",
    "Landroid/media/AudioAttributes$Builder;",
    "Landroid/media/AudioAttributes;",
    "Landroid/media/AudioDeviceInfo;",
    "Landroid/media/AudioManager$OnAudioFocusChangeListener;",
    "Landroid/media/AudioManager;",
    "Landroid/media/AudioTimestamp;",
    "Landroid/media/AudioTrack$StreamEventCallback;",
    "Landroid/media/AudioTrack;",
    "Landroid/media/Image;",
    "Landroid/media/ImageReader$OnImageAvailableListener;",
    "Landroid/media/ImageReader;",
    "Landroid/media/MediaCodec$BufferInfo;",
    "Landroid/media/MediaCodec$CryptoInfo$Pattern;",
    "Landroid/media/MediaCodec$CryptoInfo;",
    "Landroid/media/MediaCodec;",
    "Landroid/media/MediaCodecInfo$CodecCapabilities;",
    "Landroid/media/MediaCrypto;",
    "Landroid/media/MediaDrm;",
    "Landroid/media/MediaExtractor;",
    "Landroid/media/MediaFormat;",
    "Landroid/media/MediaMuxer;",
    "Landroid/media/MediaPlayer$OnBufferingUpdateListener;",
    "Landroid/media/MediaPlayer$OnCompletionListener;",
    "Landroid/media/MediaPlayer$OnErrorListener;",
    "Landroid/media/MediaPlayer$OnInfoListener;",
    "Landroid/media/MediaPlayer$OnPreparedListener;",
    "Landroid/media/MediaPlayer$OnVideoSizeChangedListener;",
    "Landroid/media/MediaPlayer;",
    "Landroid/media/MediaRecorder$OnErrorListener;",
    "Landroid/media/MediaRecorder$OnInfoListener;",
    "Landroid/media/MediaRecorder;",
    "Landroid/media/MediaScannerConnection;",
    "Landroid/media/metrics/LogSessionId;",
    "Landroid/media/projection/MediaProjection;",
    "Landroid/net/compatibility/WebAddress;",
    "Landroid/net/ConnectivityManager;",
    "Landroid/net/http/AndroidHttpClient$LoggingConfiguration;",
    "Landroid/net/http/AndroidHttpClient;",
    "Landroid/net/http/AndroidHttpClientConnection;",
    "Landroid/net/http/CertificateChainValidator;",
    "Landroid/net/http/Connection;",
    "Landroid/net/http/EventHandler;",
    "Landroid/net/http/IdleCache$IdleReaper;",
    "Landroid/net/http/IdleCache;",
    "Landroid/net/http/Request;",
    "Landroid/net/http/RequestFeeder;",
    "Landroid/net/http/RequestQueue$ActivePool;",
    "Landroid/net/http/RequestQueue$ConnectionManager;",
    "Landroid/net/http/RequestQueue;",
    "Landroid/net/http/SslCertificate;",
    "Landroid/net/http/X509TrustManagerExtensions;",
    "Landroid/net/NetworkInfo;",
    "Landroid/net/Uri;",
    "Landroid/net/wifi/ScanResult;",
    "Landroid/net/wifi/WifiManager$WifiLock;",
    "Landroid/net/wifi/WifiManager;",
    "Landroid/opengl/EGLConfig;",
    "Landroid/opengl/EGLContext;",
    "Landroid/opengl/EGLDisplay;",
    "Landroid/opengl/EGLSurface;",
    "Landroid/os/Binder;",
    "Landroid/os/Bundle;",
    "Landroid/os/CancellationSignal;",
    "Landroid/os/ConditionVariable;",
    "Landroid/os/FileObserver;",
    "Landroid/os/Handler$Callback;",
    "Landroid/os/Handler;",
    "Landroid/os/HandlerThread;",
    "Landroid/os/IBinder$DeathRecipient;",
    "Landroid/os/IBinder;",
    "Landroid/os/IInterface;",
    "Landroid/os/LocaleList;",
    "Landroid/os/Looper;",
    "Landroid/os/Message;",
    "Landroid/os/MessageQueue$IdleHandler;",
    "Landroid/os/Messenger;",
    "Landroid/os/Parcel;",
    "Landroid/os/Parcelable$Creator;",
    "Landroid/os/Parcelable;",
    "Landroid/os/ParcelFileDescriptor;",
    "Landroid/os/PersistableBundle;",
    "Landroid/os/PowerManager$WakeLock;",
    "Landroid/os/PowerManager;",
    "Landroid/os/RemoteCallbackList;",
    "Landroid/os/SharedMemory;",
    "Landroid/os/StatFs;",
    "Landroid/speech/tts/TextToSpeech;",
    "Landroid/support/v4/os/IResultReceiver;",
    "Landroid/support/v4/os/ResultReceiver;",
    "Landroid/telephony/PhoneStateListener;",
    "Landroid/telephony/SubscriptionManager;",
    "Landroid/telephony/TelephonyManager;",
    "Landroid/text/Editable;",
    "Landroid/text/format/Time;",
    "Landroid/text/Layout$Alignment;",
    "Landroid/text/Layout;",
    "Landroid/text/method/KeyListener;",
    "Landroid/text/StaticLayout;",
    "Landroid/text/TextPaint;",
    "Landroid/text/TextUtils$TruncateAt;",
    "Landroid/text/TextWatcher;",
    "Landroid/util/DisplayMetrics;",
    "Landroid/util/JsonReader;",
    "Landroid/util/JsonToken;",
    "Landroid/util/LongSparseArray;",
    "Landroid/util/LruCache;",
    "Landroid/util/Pair;",
    "Landroid/util/Range;",
    "Landroid/util/SparseArray;",
    "Landroid/util/SparseBooleanArray;",
    "Landroid/util/SparseIntArray;",
    "Landroid/view/accessibility/AccessibilityManager;",
    "Landroid/view/accessibility/AccessibilityNodeInfo;",
    "Landroid/view/animation/Animation$AnimationListener;",
    "Landroid/view/animation/Animation;",
    "Landroid/view/animation/DecelerateInterpolator;",
    "Landroid/view/animation/Interpolator;",
    "Landroid/view/animation/LinearInterpolator;",
    "Landroid/view/Choreographer$FrameCallback;",
    "Landroid/view/Choreographer;",
    "Landroid/view/DisplayCutout;",
    "Landroid/view/GestureDetector$OnGestureListener;",
    "Landroid/view/GestureDetector$SimpleOnGestureListener;",
    "Landroid/view/GestureDetector;",
    "Landroid/view/LayoutInflater;",
    "Landroid/view/MotionEvent;",
    "Landroid/view/OrientationEventListener;",
    "Landroid/view/ScaleGestureDetector$SimpleOnScaleGestureListener;",
    "Landroid/view/ScaleGestureDetector;",
    "Landroid/view/Surface;",
    "Landroid/view/SurfaceControl;",
    "Landroid/view/SurfaceHolder;",
    "Landroid/view/SurfaceView;",
    "Landroid/view/TextureView$SurfaceTextureListener;",
    "Landroid/view/TextureView;",
    "Landroid/view/VelocityTracker;",
    "Landroid/view/View$AccessibilityDelegate;",
    "Landroid/view/View$OnApplyWindowInsetsListener;",
    "Landroid/view/View$OnAttachStateChangeListener;",
    "Landroid/view/View$OnClickListener;",
    "Landroid/view/View$OnFocusChangeListener;",
    "Landroid/view/View$OnLayoutChangeListener;",
    "Landroid/view/View$OnLongClickListener;",
    "Landroid/view/View$OnTouchListener;",
    "Landroid/view/View;",
    "Landroid/view/ViewGroup$MarginLayoutParams;",
    "Landroid/view/ViewGroup;",
    "Landroid/view/ViewParent;",
    "Landroid/view/ViewPropertyAnimator;",
    "Landroid/view/ViewStub;",
    "Landroid/view/ViewTreeObserver$OnGlobalLayoutListener;",
    "Landroid/view/ViewTreeObserver$OnPreDrawListener;",
    "Landroid/view/ViewTreeObserver;",
    "Landroid/view/Window;",
    "Landroid/view/WindowInsets$Builder;",
    "Landroid/view/WindowInsets;",
    "Landroid/view/WindowManager$LayoutParams;",
    "Landroid/view/WindowManager;",
    "Landroid/webkit/MimeTypeMap;",
    "Landroid/webkit/ValueCallback;",
    "Landroid/webkit/WebChromeClient$CustomViewCallback;",
    "Landroid/webkit/WebChromeClient;",
    "Landroid/webkit/WebSettings;",
    "Landroid/webkit/WebViewClient;",
    "Landroid/widget/AdapterView$OnItemClickListener;",
    "Landroid/widget/Button;",
    "Landroid/widget/CheckBox;",
    "Landroid/widget/EdgeEffect;",
    "Landroid/widget/EditText;",
    "Landroid/widget/FrameLayout$LayoutParams;",
    "Landroid/widget/FrameLayout;",
    "Landroid/widget/GridView;",
    "Landroid/widget/ImageView;",
    "Landroid/widget/LinearLayout;",
    "Landroid/widget/ListAdapter;",
    "Landroid/widget/ListView;",
    "Landroid/widget/MediaController;",
    "Landroid/widget/MultiAutoCompleteTextView$Tokenizer;",
    "Landroid/widget/OverScroller;",
    "Landroid/widget/PopupWindow;",
    "Landroid/widget/ProgressBar;",
    "Landroid/widget/RelativeLayout$LayoutParams;",
    "Landroid/widget/RelativeLayout;",
    "Landroid/widget/RemoteViews;",
    "Landroid/widget/Scroller;",
    "Landroid/widget/ScrollView;",
    "Landroid/widget/SeekBar$OnSeekBarChangeListener;",
    "Landroid/widget/SeekBar;",
    "Landroid/widget/Switch;",
    "Landroid/widget/TextView$OnEditorActionListener;",
    "Landroid/widget/TextView;",
    "Landroidx/activity/ComponentActivity;",
    "Landroidx/core/graphics/drawable/IconCompat;",
    "Landroidx/core/view/accessibility/AccessibilityNodeInfoCompat;",
    "Landroidx/customview/view/AbsSavedState;",
    "Landroidx/fragment/app/Fragment;",
    "Landroidx/fragment/app/FragmentActivity;",
    "Landroidx/lifecycle/ProcessLifecycleOwner$3;",
    "Landroidx/media/AudioAttributesCompat;",
    "Landroidx/media/AudioAttributesImpl;",
    "Landroidx/recyclerview/widget/LinearLayoutManager$SavedState;",
    "Landroidx/recyclerview/widget/RecyclerView$SavedState;",
    "Landroidx/recyclerview/widget/RecyclerView;",
    "Landroidx/recyclerview/widget/StaggeredGridLayoutManager$SavedState;",
    "Landroidx/recyclerview/widget/StaggeredGridLayoutManager;",
    "Landroidx/room/IMultiInstanceInvalidationService$Stub;",
    "Landroidx/room/MultiInstanceInvalidationService;",
    "Lcom/android/internal/http/multipart/PartSource;",
    "Lcom/bloks/foa/components/bottomsheet/ViewDragHelper$Callback;",
    "Lcom/bloks/stdlib/components/bkcomponentscollection/StickyHeadersLinearLayoutManager;",
    "Lcom/bloks/stdlib/components/bkcomponentstextinput/BloksEditText;",
    "Lcom/facebook/blescan/BleScanOperation;",
    "Lcom/facebook/bugreporterlite/BugReport;",
    "Lcom/facebook/common/callercontext/CallerContext;",
    "Lcom/facebook/common/callercontext/ContextChain;",
    "Lcom/facebook/common/time/AwakeTimeSinceBootClock;",
    "Lcom/facebook/common/time/RealtimeSinceBootClock;",
    "Lcom/facebook/errorreporting/lacrima/detector/javacrash/JavaCrashDetector;",
    "Lcom/facebook/exoplayer/bandwidthestimator/estimate/VideoBandwidthEstimate;",
    "Lcom/facebook/exoplayer/formatevaluator/configuration/AbrContextAwareConfiguration;",
    "Lcom/facebook/exoplayer/monitor/VpsEventCallback;",
    "Lcom/facebook/ffmpeg/FFMpegMediaDemuxer$Options;",
    "Lcom/facebook/ffmpeg/FFMpegMediaMuxer$NativeWrapper;",
    "Lcom/facebook/flexlayout/layoutoutput/LayoutOutput;",
    "Lcom/facebook/fresco/animation/factory/AnimatedFactoryV2Impl;",
    "Lcom/facebook/http/historical/NetworkInfoMap;",
    "Lcom/facebook/iabeventlogging/model/IABEmptyEvent;",
    "Lcom/facebook/infer/annotation/Nullsafe$Mode;",
    "Lcom/facebook/inject/FbInjector;",
    "Lcom/facebook/lite/AppController$NetworkStateBroadcastReceiver;",
    "Lcom/facebook/lite/background/DelayedBackgroundDetector;",
    "Lcom/facebook/lite/bloks/LiteBloksManager;",
    "Lcom/facebook/lite/browser/BrowserLiteCallbackService;",
    "Lcom/facebook/lite/camera/wrapper/camera/views/CameraView;",
    "Lcom/facebook/lite/camera/wrapper/camera/views/FocusIndicatorView;",
    "Lcom/facebook/lite/camera/wrapper/camera/views/SquareCaptureButtonView;",
    "Lcom/facebook/lite/ClientApplication;",
    "Lcom/facebook/lite/ClientApplicationSplittedShell;",
    "Lcom/facebook/lite/common/AndroidDeviceUtil;",
    "Lcom/facebook/lite/components/ComponentsRendererManager;",
    "Lcom/facebook/lite/components/scroll/AbsoluteLayoutManager;",
    "Lcom/facebook/lite/components/scroll/twowayview/TwoWayLayoutManager$SavedState;",
    "Lcom/facebook/lite/components/scroll/twowayview/TwoWayLayoutManager;",
    "Lcom/facebook/lite/components/text/LiteEditTextView;",
    "Lcom/facebook/lite/components/web/WebProps;",
    "Lcom/facebook/lite/deviceid/FbLitePhoneIdStore;",
    "Lcom/facebook/lite/deviceid/FbLitePhoneIdUpdatedCallback;",
    "Lcom/facebook/lite/deviceid/FbLitePhoneIdUpdater;",
    "Lcom/facebook/lite/download/DownloadManager;",
    "Lcom/facebook/lite/download/DownloadService;",
    "Lcom/facebook/lite/FBLiteMainActivity;",
    "Lcom/facebook/lite/FbnsIntentService$CallbackReceiver;",
    "Lcom/facebook/lite/feo2/FeO2ContentProviderDelegate;",
    "Lcom/facebook/lite/ForegroundService;",
    "Lcom/facebook/lite/heroplayer/impl/FbLiteHeroServiceEventReceiver;",
    "Lcom/facebook/lite/loginWithFacebook/wrapper/AccessToken;",
    "Lcom/facebook/lite/loginWithFacebook/wrapper/LoginClient$Request;",
    "Lcom/facebook/lite/loginWithFacebook/wrapper/LoginClient;",
    "Lcom/facebook/lite/loginWithFacebook/wrapper/LoginWithFBActivityImpl;",
    "Lcom/facebook/lite/media/AlbumGalleryActivity;",
    "Lcom/facebook/lite/msys/analytics/notification/SecureMessageOverWANotificationsE2ELogger;",
    "Lcom/facebook/lite/msys/analytics/notification/SecureMessageOverWANotificationsE2EMessageLevelLogger;",
    "Lcom/facebook/lite/msys/provider/MsysProvider;",
    "Lcom/facebook/lite/nativeRtc/NativeRtcCallActivity;",
    "Lcom/facebook/lite/nativeRtc/receiver/NotificationActionReceiver;",
    "Lcom/facebook/lite/net/TcpGatewayConnector;",
    "Lcom/facebook/lite/notification/ActiveNotificationsManager;",
    "Lcom/facebook/lite/notification/LiteFirebaseMessagingService;",
    "Lcom/facebook/lite/notification/messaging/ArmadilloNotificationForegroundService;",
    "Lcom/facebook/lite/notification/NotificationSchedulingReceiver;",
    "Lcom/facebook/lite/notification/widget/receiver/NotificationsWidgetProvider;",
    "Lcom/facebook/lite/openzeroratedcheckoutactivity/OpenZeroRatedCheckoutActivity;",
    "Lcom/facebook/lite/phonenumberhint/PhoneNumberHint;",
    "Lcom/facebook/lite/photoview/PhotoView;",
    "Lcom/facebook/lite/platform/LoginGDPDialogActivityV2;",
    "Lcom/facebook/lite/reliablemedia/ReliableMediaManager$Companion;",
    "Lcom/facebook/lite/reliablemedia/ReliableMediaManager;",
    "Lcom/facebook/lite/reliablemedia/RMDResult$FallbackStats;",
    "Lcom/facebook/lite/rtc/impl/service/RtcService;",
    "Lcom/facebook/lite/ScreenChangeDataParcelable;",
    "Lcom/facebook/lite/service/AppRestartService;",
    "Lcom/facebook/lite/service/NotificationQuickActionService;",
    "Lcom/facebook/lite/storagemanager/ClearStorageCheckbox;",
    "Lcom/facebook/lite/storagemanager/ManageStorageActivity;",
    "Lcom/facebook/lite/testing/TestRun;",
    "Lcom/facebook/lite/util/LayoutBuilder/GenericVideoViewViewBinder;",
    "Lcom/facebook/lite/util/LayoutBuilder/SpinnerViewViewBinder;",
    "Lcom/facebook/lite/video/cache/ChunkedPartialFileStorage;",
    "Lcom/facebook/lite/webviewholder/WebviewCustomViewHolder;",
    "Lcom/facebook/lite/webviewholder/WebviewFullScreenCustomViewHolder;",
    "Lcom/facebook/lite/webviewrtc/IncomingCallContext;",
    "Lcom/facebook/lite/webviewrtc/P2PJavaScriptInterface;",
    "Lcom/facebook/lite/webviewrtc/RoomMetaData;",
    "Lcom/facebook/lite/webviewrtc/RTCIncomingCallActivity;",
    "Lcom/facebook/lite/webviewrtc/RTCService;",
    "Lcom/facebook/lite/webviewrtc/RTCWebView$RTCJavaScriptInterface;",
    "Lcom/facebook/lite/webviewrtc/RTCWebView;",
    "Lcom/facebook/lite/widget/DummySurfaceView;",
    "Lcom/facebook/lite/widget/FbInlineWebView;",
    "Lcom/facebook/lite/widget/FbWebView;",
    "Lcom/facebook/lite/widget/FloatingTextBox;",
    "Lcom/facebook/lite/widget/GalleryImageView;",
    "Lcom/facebook/lite/widget/HorizontalProgressBar;",
    "Lcom/facebook/lite/widget/InlineTextBox;",
    "Lcom/facebook/lite/widget/LiveStreamingView;",
    "Lcom/facebook/lite/widget/mediapicker/HeaderGridRecyclerView;",
    "Lcom/facebook/lite/widget/mediapicker/MediaPickerRecyclerView;",
    "Lcom/facebook/lite/widget/ProgressBarView;",
    "Lcom/facebook/lite/widget/RoundedIconImageView;",
    "Lcom/facebook/lite/widget/ScreenTransitionLoadingViewV2;",
    "Lcom/facebook/lite/widget/video/FBFullScreenVideoView;",
    "Lcom/facebook/lite/widget/video/FbVideoView;",
    "Lcom/facebook/location/appstate/GeoApiLocationAppStateListener$LifecycleCallback;",
    "Lcom/facebook/mobileidservices/feo2/core/controller/FeO2ClientController;",
    "Lcom/facebook/onecamera/corecomponents/threading/basic/ThreadPoolImpl$LifeStatus;",
    "Lcom/facebook/photos/upload/mediaqualitykit/liteimagequalityutils/ImageQualityUtils;",
    "Lcom/facebook/privacy/zone/api/ZonedValue;",
    "Lcom/facebook/privacy/zone/policy/ZonePolicy;",
    "Lcom/facebook/push/fbns/ipc/IFbnsAIDLService$Stub;",
    "Lcom/facebook/quicklog/EventBuilder;",
    "Lcom/facebook/quicklog/LightweightQuickPerformanceLogger;",
    "Lcom/facebook/quicklog/QuickPerformanceLogger;",
    "Lcom/facebook/quicklog/reliability/UserFlowLogger;",
    "Lcom/facebook/rendercore/MountItemsPool$PoolsActivityCallback;",
    "Lcom/facebook/rendercore/RenderTreeNode;",
    "Lcom/facebook/rendercore/text/RCTextView;",
    "Lcom/facebook/rti/common/time/RealtimeSinceBootClock;",
    "Lcom/facebook/rti/mqtt/manager/MqttBackgroundServiceDelegate;",
    "Lcom/facebook/rti/mqtt/manager/MqttPushServiceDelegate;",
    "Lcom/facebook/rti/mqtt/protocol/messages/TopicExtraInfo;",
    "Lcom/facebook/rti/push/service/FbnsServiceDelegate;",
    "Lcom/facebook/rti/push/service/MqttSystemBroadcastReceiver;",
    "Lcom/facebook/secure/fileprovider/SecureFileProvider;",
    "Lcom/facebook/stash/core/Stash;",
    "Lcom/facebook/superpack/SuperpackFile;",
    "Lcom/facebook/superpack/SuperpackFileLoader;",
    "Lcom/facebook/ui/emoji/model/Emoji;",
    "Lcom/facebook/video/grootplayer/loggersdk/VideoPlayerSessionLogger;",
    "Lcom/facebook/video/heroplayer/common/GlobalPlayerStateMonitor;",
    "Lcom/facebook/video/heroplayer/ipc/AudioFocusLossSettings;",
    "Lcom/facebook/video/heroplayer/ipc/LiveState;",
    "Lcom/facebook/video/heroplayer/ipc/ParcelableFormat;",
    "Lcom/facebook/video/heroplayer/ipc/ServicePlayerState;",
    "Lcom/facebook/video/heroplayer/ipc/VideoMemoryState;",
    "Lcom/facebook/video/heroplayer/ipc/VideoPlayContextualSetting;",
    "Lcom/facebook/video/heroplayer/ipc/VideoPlayRequest;",
    "Lcom/facebook/video/heroplayer/ipc/VideoPrefetchRequest;",
    "Lcom/facebook/video/heroplayer/ipc/VideoSource;",
    "Lcom/facebook/video/heroplayer/service/live/HeroDashLiveManagerImpl;",
    "Lcom/facebook/video/heroplayer/service/ServiceEventCallbackImpl;",
    "Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;",
    "Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;",
    "Lcom/facebook/video/jni/VideoJni;",
    "Lcom/facebook/videolite/api/asset/MediaAssetData;",
    "Lcom/facebook/videolite/api/asset/MediaAssetDataSerializer;",
    "Lcom/facebook/videolite/api/jobscheduler/UploadJobSchedulerService;",
    "Lcom/facebook/videolite/transcoder/base/composition/MediaEffect;",
    "Lcom/facebook/videolite/transcoder/base/SphericalMetadata;",
    "Lcom/facebook/voltron/download/scheduledinstaller/OxygenScheduledInstallerJobService;",
    "Lcom/google/android/exoplayer2/audio/DefaultAudioSink;",
    "Lcom/google/android/exoplayer2/drm/DrmInitData;",
    "Lcom/google/android/exoplayer2/extractor/mkv/MatroskaExtractor;",
    "Lcom/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor2;",
    "Lcom/google/android/exoplayer2/FbFormatExtension;",
    "Lcom/google/android/exoplayer2/Format;",
    "Lcom/google/android/exoplayer2/metadata/Metadata;",
    "Lcom/google/android/exoplayer2/source/TrackGroup;",
    "Lcom/google/android/exoplayer2/source/TrackGroupArray;",
    "Lcom/google/android/exoplayer2/Timeline;",
    "Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector$Parameters;",
    "Lcom/google/android/exoplayer2/video/ColorInfo;",
    "Lcom/google/android/exoplayer2/video/DummySurface;",
    "Lcom/google/android/finsky/externalreferrer/IGetInstallReferrerService;",
    "Lcom/google/android/gms/auth/api/credentials/Credential;",
    "Lcom/google/android/gms/auth/api/credentials/CredentialPickerConfig;",
    "Lcom/google/android/gms/auth/api/credentials/CredentialRequest;",
    "Lcom/google/android/gms/auth/api/identity/GetPhoneNumberHintIntentRequest;",
    "Lcom/google/android/gms/auth/api/signin/GoogleSignInAccount;",
    "Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;",
    "Lcom/google/android/gms/auth/api/signin/internal/SignInConfiguration;",
    "Lcom/google/android/gms/auth/api/signin/internal/SignInHubActivity;",
    "Lcom/google/android/gms/common/api/internal/BackgroundDetector;",
    "Lcom/google/android/gms/common/api/internal/BasePendingResult;",
    "Lcom/google/android/gms/common/api/internal/LifecycleCallback;",
    "Lcom/google/android/gms/common/api/internal/zact;",
    "Lcom/google/android/gms/common/api/Scope;",
    "Lcom/google/android/gms/common/api/Status;",
    "Lcom/google/android/gms/common/ConnectionResult;",
    "Lcom/google/android/gms/common/data/DataHolder;",
    "Lcom/google/android/gms/common/Feature;",
    "Lcom/google/android/gms/common/GoogleApiAvailability;",
    "Lcom/google/android/gms/common/internal/ConnectionTelemetryConfiguration;",
    "Lcom/google/android/gms/common/internal/IAccountAccessor;",
    "Lcom/google/android/gms/common/internal/IGmsServiceBroker;",
    "Lcom/google/android/gms/common/internal/MethodInvocation;",
    "Lcom/google/android/gms/common/internal/RootTelemetryConfiguration;",
    "Lcom/google/android/gms/common/internal/TelemetryData;",
    "Lcom/google/android/gms/common/internal/zat;",
    "Lcom/google/android/gms/common/internal/zav;",
    "Lcom/google/android/gms/common/internal/zzj;",
    "Lcom/google/android/gms/common/zzl;",
    "Lcom/google/android/gms/internal/auth/zzcb;",
    "Lcom/google/android/gms/internal/safetynet/zzg;",
    "Lcom/google/android/gms/safetynet/zza;",
    "Lcom/google/android/gms/signin/internal/zak;",
    "Lcom/google/android/play/core/splitinstall/zzaa;",
    "Lcom/google/android/play/core/splitinstall/zzbi;",
    "Lcom/google/common/collect/AbstractMapBasedMultimap;",
    "Lcom/google/common/collect/CompactHashMap;",
    "Lcom/google/common/collect/CompactHashSet;",
    "Lcom/google/common/collect/EmptyImmutableSetMultimap;",
    "Lcom/google/common/collect/EvictingQueue;",
    "Lcom/google/common/collect/ImmutableCollection;",
    "Lcom/google/common/collect/ImmutableList;",
    "Lcom/google/common/collect/ImmutableMap;",
    "Lcom/google/common/collect/ImmutableSet;",
    "Lcom/google/common/collect/ImmutableSetMultimap;",
    "Lcom/google/common/collect/ImmutableSortedSet;",
    "Lcom/google/common/collect/Maps$EntryFunction;",
    "Lcom/google/common/collect/NaturalOrdering;",
    "Lcom/google/common/collect/RegularImmutableBiMap;",
    "Lcom/google/common/collect/RegularImmutableMap$EntrySet;",
    "Lcom/google/common/collect/RegularImmutableSet;",
    "Lcom/google/common/collect/RegularImmutableSortedSet;",
    "Lcom/google/common/collect/ReverseNaturalOrdering;",
    "Lcom/google/errorprone/annotations/Modifier;",
    "Lcom/google/firebase/components/ComponentRegistrar;",
    "Lcom/google/firebase/iid/FirebaseInstanceId;",
    "Lcom/google/firebase/iid/zzm;",
    "Lcom/google/firebase/messaging/RemoteMessage;",
    "Lcom/google/j2objc/annotations/LoopTranslation$LoopStyle;",
    "Lcom/google/j2objc/annotations/ReflectionSupport$Level;",
    "Lcom/jakewharton/disklrucache_fb/DiskLruCache;",
    "Lcom/meta/foa/cds/bottomsheet/theming/CdsBottomSheetThemeConfig$CdsColorData;",
    "Lcom/meta/foa/cds/CdsOpenScreenCallerDismissCallback;",
    "Lcom/moblica/common/xmob/ui/WindowManager;",
    "Lexoplayer2/av1/src/Dav1dScalingMode;",
    "Ljava/io/ByteArrayOutputStream;",
    "Ljava/io/Closeable;",
    "Ljava/io/DataInputStream;",
    "Ljava/io/DataOutputStream;",
    "Ljava/io/File;",
    "Ljava/io/FileDescriptor;",
    "Ljava/io/FileFilter;",
    "Ljava/io/FileInputStream;",
    "Ljava/io/FilenameFilter;",
    "Ljava/io/FileOutputStream;",
    "Ljava/io/InputStream;",
    "Ljava/io/IOException;",
    "Ljava/io/OutputStream;",
    "Ljava/io/PipedOutputStream;",
    "Ljava/io/PrintStream;",
    "Ljava/io/PrintWriter;",
    "Ljava/io/RandomAccessFile;",
    "Ljava/io/Reader;",
    "Ljava/io/Serializable;",
    "Ljava/io/StringWriter;",
    "Ljava/io/Writer;",
    "Ljava/lang/Boolean;",
    "Ljava/lang/Byte;",
    "Ljava/lang/Character;",
    "Ljava/lang/CharSequence;",
    "Ljava/lang/Class;",
    "Ljava/lang/ClassLoader;",
    "Ljava/lang/Double;",
    "Ljava/lang/Error;",
    "Ljava/lang/Exception;",
    "Ljava/lang/Float;",
    "Ljava/lang/Integer;",
    "Ljava/lang/Iterable;",
    "Ljava/lang/Long;",
    "Ljava/lang/NullPointerException;",
    "Ljava/lang/Object;",
    "Ljava/lang/ref/ReferenceQueue;",
    "Ljava/lang/ref/WeakReference;",
    "Ljava/lang/reflect/Constructor;",
    "Ljava/lang/reflect/Field;",
    "Ljava/lang/reflect/Method;",
    "Ljava/lang/Runnable;",
    "Ljava/lang/Runtime;",
    "Ljava/lang/RuntimeException;",
    "Ljava/lang/Short;",
    "Ljava/lang/String;",
    "Ljava/lang/StringBuffer;",
    "Ljava/lang/StringBuilder;",
    "Ljava/lang/Thread$UncaughtExceptionHandler;",
    "Ljava/lang/Thread;",
    "Ljava/lang/ThreadGroup;",
    "Ljava/lang/ThreadLocal;",
    "Ljava/lang/Throwable;",
    "Ljava/lang/UnsatisfiedLinkError;",
    "Ljava/math/BigDecimal;",
    "Ljava/math/BigInteger;",
    "Ljava/net/DatagramPacket;",
    "Ljava/net/DatagramSocket;",
    "Ljava/net/HttpURLConnection;",
    "Ljava/net/InetAddress;",
    "Ljava/net/InetSocketAddress;",
    "Ljava/net/MulticastSocket;",
    "Ljava/net/Proxy;",
    "Ljava/net/ProxySelector;",
    "Ljava/net/ServerSocket;",
    "Ljava/net/Socket;",
    "Ljava/net/URI;",
    "Ljava/net/URL;",
    "Ljava/nio/ByteBuffer;",
    "Ljava/nio/ByteOrder;",
    "Ljava/nio/channels/FileChannel;",
    "Ljava/nio/channels/FileLock;",
    "Ljava/nio/CharBuffer;",
    "Ljava/nio/charset/Charset;",
    "Ljava/nio/charset/CharsetDecoder;",
    "Ljava/nio/FloatBuffer;",
    "Ljava/nio/IntBuffer;",
    "Ljava/nio/MappedByteBuffer;",
    "Ljava/nio/ShortBuffer;",
    "Ljava/security/cert/Certificate;",
    "Ljava/security/KeyPair;",
    "Ljava/security/KeyStore;",
    "Ljava/security/MessageDigest;",
    "Ljava/security/Permission;",
    "Ljava/security/PublicKey;",
    "Ljava/security/SecureRandom;",
    "Ljava/text/DateFormat;",
    "Ljava/text/SimpleDateFormat;",
    "Ljava/util/ArrayDeque;",
    "Ljava/util/ArrayList;",
    "Ljava/util/BitSet;",
    "Ljava/util/Calendar;",
    "Ljava/util/Collection;",
    "Ljava/util/Comparator;",
    "Ljava/util/concurrent/atomic/AtomicBoolean;",
    "Ljava/util/concurrent/atomic/AtomicInteger;",
    "Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;",
    "Ljava/util/concurrent/atomic/AtomicLong;",
    "Ljava/util/concurrent/atomic/AtomicLongArray;",
    "Ljava/util/concurrent/atomic/AtomicReference;",
    "Ljava/util/concurrent/atomic/AtomicReferenceArray;",
    "Ljava/util/concurrent/atomic/AtomicReferenceFieldUpdater;",
    "Ljava/util/concurrent/BlockingDeque;",
    "Ljava/util/concurrent/BlockingQueue;",
    "Ljava/util/concurrent/Callable;",
    "Ljava/util/concurrent/CancellationException;",
    "Ljava/util/concurrent/ConcurrentHashMap;",
    "Ljava/util/concurrent/ConcurrentLinkedDeque;",
    "Ljava/util/concurrent/ConcurrentLinkedQueue;",
    "Ljava/util/concurrent/ConcurrentMap;",
    "Ljava/util/concurrent/CopyOnWriteArrayList;",
    "Ljava/util/concurrent/CopyOnWriteArraySet;",
    "Ljava/util/concurrent/CountDownLatch;",
    "Ljava/util/concurrent/Executor;",
    "Ljava/util/concurrent/ExecutorService;",
    "Ljava/util/concurrent/Future;",
    "Ljava/util/concurrent/FutureTask;",
    "Ljava/util/concurrent/LinkedBlockingQueue;",
    "Ljava/util/concurrent/locks/Condition;",
    "Ljava/util/concurrent/locks/Lock;",
    "Ljava/util/concurrent/locks/ReentrantLock;",
    "Ljava/util/concurrent/locks/ReentrantReadWriteLock;",
    "Ljava/util/concurrent/PriorityBlockingQueue;",
    "Ljava/util/concurrent/RunnableFuture;",
    "Ljava/util/concurrent/ScheduledExecutorService;",
    "Ljava/util/concurrent/ScheduledFuture;",
    "Ljava/util/concurrent/Semaphore;",
    "Ljava/util/concurrent/ThreadFactory;",
    "Ljava/util/concurrent/ThreadPoolExecutor;",
    "Ljava/util/concurrent/TimeUnit;",
    "Ljava/util/Date;",
    "Ljava/util/Deque;",
    "Ljava/util/Enumeration;",
    "Ljava/util/EnumMap;",
    "Ljava/util/EnumSet;",
    "Ljava/util/Formatter;",
    "Ljava/util/HashMap;",
    "Ljava/util/HashSet;",
    "Ljava/util/Hashtable;",
    "Ljava/util/IdentityHashMap;",
    "Ljava/util/Iterator;",
    "Ljava/util/LinkedHashMap;",
    "Ljava/util/LinkedHashSet;",
    "Ljava/util/LinkedList;",
    "Ljava/util/List;",
    "Ljava/util/Locale;",
    "Ljava/util/logging/Level;",
    "Ljava/util/logging/Logger;",
    "Ljava/util/Map$Entry;",
    "Ljava/util/Map;",
    "Ljava/util/PriorityQueue;",
    "Ljava/util/Properties;",
    "Ljava/util/Queue;",
    "Ljava/util/Random;",
    "Ljava/util/regex/Pattern;",
    "Ljava/util/Set;",
    "Ljava/util/SortedSet;",
    "Ljava/util/Stack;",
    "Ljava/util/Timer;",
    "Ljava/util/TimeZone;",
    "Ljava/util/TreeMap;",
    "Ljava/util/TreeSet;",
    "Ljava/util/UUID;",
    "Ljava/util/WeakHashMap;",
    "Ljava/util/zip/CRC32;",
    "Ljava/util/zip/Inflater;",
    "Ljava/util/zip/ZipEntry;",
    "Ljava/util/zip/ZipFile;",
    "Ljavax/crypto/spec/IvParameterSpec;",
    "Ljavax/microedition/khronos/egl/EGL10;",
    "Ljavax/net/SocketFactory;",
    "Ljavax/net/ssl/HostnameVerifier;",
    "Ljavax/net/ssl/SSLSocketFactory;",
    "Ljavax/net/ssl/X509TrustManager;",
    "Lokhttp3/internal/publicsuffix/PublicSuffixDatabase;",
    "Lorg/apache/commons/codec/language/DoubleMetaphone;",
    "Lorg/apache/commons/codec/language/RefinedSoundex;",
    "Lorg/apache/commons/codec/language/Soundex;",
    "Lorg/apache/commons/codec/StringEncoder;",
    "Lorg/apache/commons/logging/impl/WeakHashtable$Referenced;",
    "Lorg/apache/commons/logging/impl/WeakHashtable;",
    "Lorg/apache/commons/logging/Log;",
    "Lorg/apache/commons/logging/LogFactory;",
    "Lorg/apache/http/auth/AuthScheme;",
    "Lorg/apache/http/auth/AuthSchemeRegistry;",
    "Lorg/apache/http/auth/AuthScope;",
    "Lorg/apache/http/auth/AuthState;",
    "Lorg/apache/http/auth/BasicUserPrincipal;",
    "Lorg/apache/http/auth/Credentials;",
    "Lorg/apache/http/auth/NTUserPrincipal;",
    "Lorg/apache/http/client/AuthenticationHandler;",
    "Lorg/apache/http/client/CookieStore;",
    "Lorg/apache/http/client/CredentialsProvider;",
    "Lorg/apache/http/client/HttpClient;",
    "Lorg/apache/http/client/HttpRequestRetryHandler;",
    "Lorg/apache/http/client/RedirectHandler;",
    "Lorg/apache/http/client/UserTokenHandler;",
    "Lorg/apache/http/conn/ClientConnectionManager;",
    "Lorg/apache/http/conn/ClientConnectionOperator;",
    "Lorg/apache/http/conn/ClientConnectionRequest;",
    "Lorg/apache/http/conn/ConnectionKeepAliveStrategy;",
    "Lorg/apache/http/conn/ConnectionReleaseTrigger;",
    "Lorg/apache/http/conn/EofSensorWatcher;",
    "Lorg/apache/http/conn/ManagedClientConnection;",
    "Lorg/apache/http/conn/MultihomePlainSocketFactory;",
    "Lorg/apache/http/conn/OperatedClientConnection;",
    "Lorg/apache/http/conn/params/ConnPerRoute;",
    "Lorg/apache/http/conn/routing/HttpRoute;",
    "Lorg/apache/http/conn/routing/HttpRoutePlanner;",
    "Lorg/apache/http/conn/routing/RouteInfo$LayerType;",
    "Lorg/apache/http/conn/routing/RouteInfo$TunnelType;",
    "Lorg/apache/http/conn/routing/RouteTracker;",
    "Lorg/apache/http/conn/scheme/HostNameResolver;",
    "Lorg/apache/http/conn/scheme/PlainSocketFactory;",
    "Lorg/apache/http/conn/scheme/SchemeRegistry;",
    "Lorg/apache/http/conn/scheme/SocketFactory;",
    "Lorg/apache/http/conn/ssl/AbstractVerifier;",
    "Lorg/apache/http/ConnectionReuseStrategy;",
    "Lorg/apache/http/cookie/CookiePathComparator;",
    "Lorg/apache/http/cookie/CookieSpecRegistry;",
    "Lorg/apache/http/entity/ContentLengthStrategy;",
    "Lorg/apache/http/entity/ContentProducer;",
    "Lorg/apache/http/Header;",
    "Lorg/apache/http/HeaderElement;",
    "Lorg/apache/http/HeaderIterator;",
    "Lorg/apache/http/HttpEntity;",
    "Lorg/apache/http/HttpHost;",
    "Lorg/apache/http/HttpRequest;",
    "Lorg/apache/http/HttpRequestFactory;",
    "Lorg/apache/http/HttpRequestInterceptor;",
    "Lorg/apache/http/HttpResponse;",
    "Lorg/apache/http/HttpResponseFactory;",
    "Lorg/apache/http/HttpVersion;",
    "Lorg/apache/http/impl/auth/NTLMEngine;",
    "Lorg/apache/http/impl/auth/NTLMScheme$State;",
    "Lorg/apache/http/impl/client/RequestWrapper;",
    "Lorg/apache/http/impl/conn/AbstractPoolEntry;",
    "Lorg/apache/http/impl/conn/IdleConnectionHandler;",
    "Lorg/apache/http/impl/conn/SingleClientConnManager$ConnAdapter;",
    "Lorg/apache/http/impl/conn/SingleClientConnManager$PoolEntry;",
    "Lorg/apache/http/impl/conn/SingleClientConnManager;",
    "Lorg/apache/http/impl/conn/tsccm/AbstractConnPool;",
    "Lorg/apache/http/impl/conn/tsccm/BasicPoolEntryRef;",
    "Lorg/apache/http/impl/conn/tsccm/ConnPoolByRoute;",
    "Lorg/apache/http/impl/conn/tsccm/PoolEntryRequest;",
    "Lorg/apache/http/impl/conn/tsccm/RefQueueHandler;",
    "Lorg/apache/http/impl/conn/tsccm/RefQueueWorker;",
    "Lorg/apache/http/impl/conn/tsccm/RouteSpecificPool;",
    "Lorg/apache/http/impl/conn/tsccm/ThreadSafeClientConnManager;",
    "Lorg/apache/http/impl/conn/tsccm/WaitingThread;",
    "Lorg/apache/http/impl/conn/tsccm/WaitingThreadAborter;",
    "Lorg/apache/http/impl/conn/Wire;",
    "Lorg/apache/http/impl/cookie/BrowserCompatSpec;",
    "Lorg/apache/http/impl/cookie/NetscapeDraftHeaderParser;",
    "Lorg/apache/http/impl/cookie/NetscapeDraftSpec;",
    "Lorg/apache/http/impl/cookie/RFC2965Spec;",
    "Lorg/apache/http/impl/EnglishReasonPhraseCatalog;",
    "Lorg/apache/http/impl/entity/EntityDeserializer;",
    "Lorg/apache/http/impl/entity/EntitySerializer;",
    "Lorg/apache/http/impl/HttpConnectionMetricsImpl;",
    "Lorg/apache/http/impl/io/HttpTransportMetricsImpl;",
    "Lorg/apache/http/io/HttpMessageParser;",
    "Lorg/apache/http/io/HttpMessageWriter;",
    "Lorg/apache/http/io/HttpTransportMetrics;",
    "Lorg/apache/http/io/SessionInputBuffer;",
    "Lorg/apache/http/io/SessionOutputBuffer;",
    "Lorg/apache/http/message/BasicHeaderValueFormatter;",
    "Lorg/apache/http/message/BasicHeaderValueParser;",
    "Lorg/apache/http/message/BasicHttpRequest;",
    "Lorg/apache/http/message/BasicLineFormatter;",
    "Lorg/apache/http/message/BasicLineParser;",
    "Lorg/apache/http/message/HeaderGroup;",
    "Lorg/apache/http/message/HeaderValueParser;",
    "Lorg/apache/http/message/LineFormatter;",
    "Lorg/apache/http/message/LineParser;",
    "Lorg/apache/http/message/ParserCursor;",
    "Lorg/apache/http/params/HttpParams;",
    "Lorg/apache/http/protocol/BasicHttpProcessor;",
    "Lorg/apache/http/protocol/HttpContext;",
    "Lorg/apache/http/protocol/HttpDateGenerator;",
    "Lorg/apache/http/protocol/HttpExpectationVerifier;",
    "Lorg/apache/http/protocol/HttpProcessor;",
    "Lorg/apache/http/protocol/HttpRequestExecutor;",
    "Lorg/apache/http/protocol/HttpRequestHandlerResolver;",
    "Lorg/apache/http/protocol/RequestContent;",
    "Lorg/apache/http/protocol/UriPatternMatcher;",
    "Lorg/apache/http/ProtocolVersion;",
    "Lorg/apache/http/ReasonPhraseCatalog;",
    "Lorg/apache/http/RequestLine;",
    "Lorg/apache/http/StatusLine;",
    "Lorg/apache/http/util/ByteArrayBuffer;",
    "Lorg/apache/http/util/CharArrayBuffer;",
    "Lorg/chromium/support_lib_boundary/WebViewProviderFactoryBoundaryInterface;",
    "Lorg/json/JSONArray;",
    "Lorg/json/JSONObject;",
    "Lorg/xmlpull/v1/XmlPullParser;",
    "Lorg/xmlpull/v1/XmlPullParserFactory;",
    "Lsun/misc/Unsafe;",
]

ClzSign2HashMap = {}
ClzSign2HashIdx = 0

for item in BaseTypes:
    ClzSign2HashIdx += 1
    ClzSign2HashMap[item] = ClzSign2HashIdx


def getClzSignHash(clzSign):
    if not ClzSign2HashMap.get(clzSign):
        return 0
    return ClzSign2HashMap[clzSign]


# test = set()


class FieldFeature:
    def __init__(self, field):
        self.RawName = field.getName(False)
        self.NowName = field.getName(True)
        self.ClzSign = field.getFieldType().getSignature()
        # test.add(self.ClzSign)

        feature = [getClzSignHash(self.ClzSign)]
        flag = 0
        if field.getData().isFinal():
            flag |= 0b1
        if field.getData().isPrivate():
            flag |= 0b10
        if field.getData().isProtected():
            flag |= 0b100
        if field.getData().isPublic():
            flag |= 0b1000
        if field.getData().isStatic():
            flag |= 0b10000
        if field.getData().isSynthetic():
            flag |= 0b100000
        if field.getData().isVolatile():
            flag |= 0b1000000
        feature.append(flag)
        self.Feature = feature

    def hasModify(self):
        return self.RawName != self.NowName


class MethodFeature:
    def __init__(self, method):
        self.RawName = method.getName(False)
        self.NowName = method.getName(True)
        self.Sign = method.getSignature(False, True, True, True)
        self.Feature = self.makeFeature(method, self.Sign)

    def hasModify(self):
        return self.RawName != self.NowName

    def makeFeature(self, method, sign):
        sign = sign[sign.index("(") + 1:]
        sp = sign.split(")")
        retType = sp[1]
        paramsType = sp[0].split(";")
        feature = []
        flag = 0
        if method.getData().isFinal():
            flag |= 0b1
        if method.getData().isPrivate():
            flag |= 0b10
        if method.getData().isProtected():
            flag |= 0b100
        if method.getData().isPublic():
            flag |= 0b1000
        if method.getData().isStatic():
            flag |= 0b10000
        if method.getData().isSynthetic():
            flag |= 0b100000
        if method.getData().isAbstract():
            flag |= 0b1000000
        if method.getData().isConstructor():
            flag |= 0b10000000
        if method.getData().isNative():
            flag |= 0b100000000

        feature.append(flag)
        feature.append(getClzSignHash(retType))
        feature.append(-2)
        for item in paramsType:
            feature.append(getClzSignHash(item + ";"))
        return feature


class ClzFeature:
    def __init__(self, clz):
        self.RawName = clz.getName(False)
        self.NowName = clz.getName(True)
        # if self.RawName != self.NowName:
        # print(self.RawName + " - " + self.NowName)
        self.Field = []
        self.Method = []
        self.addFields(clz.getFields())
        self.addMethods(clz.getMethods())
        self.Feature = self.makeFeature(clz)

    def makeFeature(self, clz):
        feature = []
        flag = 0
        if clz.isInterface():
            flag |= 0b1
        if clz.isAnonymousClass():
            flag |= 0b10
        if clz.isInternal():
            flag |= 0b100
        if clz.isAnnotation():
            flag |= 0b1000
        feature.append(flag)
        feature.append(-5)

        for item in self.Field:
            feature.extend(item.Feature)
            feature.append(-3)

        for item in self.Method:
            feature.extend(item.Feature)
            feature.append(-4)
        return feature

    def addField(self, field):
        self.Field.append(FieldFeature(field))

    def addFields(self, fields):
        for item in fields:
            self.addField(item)

    def addMethod(self, method):
        self.Method.append(MethodFeature(method))

    def addMethods(self, methods):
        for item in methods:
            self.addMethod(item)

    def hasModify(self):
        if self.RawName != self.NowName:
            return True

        for item in self.Method:
            if item.hasModify():
                return True

        for item in self.Field:
            if item.hasModify():
                return True
        return False


class MatchClz(IScript):

    def __init__(self):
        self.ctx = None
        self.mainProject = None

    def run(self, ctx):
        self.ctx = ctx
        self.mainProject = ctx.getMainProject()

        print("ClzSign2HashIdx: " + str(ClzSign2HashIdx))
        # print("findAllChange: " + json.dumps(self.findAllChange(), cls=MyEncoder))
        # f = open(r"D:\desktop\tmp\sig\sig2.json", "w")
        # f.write(json.dumps(self.getAllClzFeature(), cls=MyEncoder))
        # f.close()

        f = open(r"D:\desktop\tmp\sig\sig1.json", "w")
        f.write(json.dumps(self.findAllChange(), cls=MyEncoder))
        f.close()
        # print(test)

    def getAllClzFeature(self):
        allClz = []
        for unit in self.mainProject.findUnits(IDexUnit):
            for c in unit.getClasses():
                clzFeature = ClzFeature(c)
                allClz.append(clzFeature)
        return allClz

    def findAllChange(self):
        allModify = []
        for unit in self.mainProject.findUnits(IDexUnit):
            for c in unit.getClasses():
                clzFeature = ClzFeature(c)
                if clzFeature.hasModify():
                    allModify.append(clzFeature)
        return allModify
