// This file was auto-generated by the internal/vendorc/vendorc.go script.
//
// This file is released under the MIT license but every source file it includes
// (directly and transitively) is in the public domain.

#ifndef GOXZ_SKIP_C_COMPILATION
#include "src/liblzma/common/index.c"
#endif
